trigger:
- main

pool: Avengers

variables:
  nodeModulesCache: $(System.DefaultWorkingDirectory)/node_modules

jobs:
  - job: BuildPublish
    displayName: Build & Publish
    steps:
      - checkout: self
        clean: false

      - task: NodeTool@0
        inputs:
          versionSpec: '12.x'
        displayName: 'Install Node.js'

      - task: Cache@2
        inputs:
          key: 'npm | "$(Agent.OS)" | package-lock.json'
          restoreKeys: |
            npm | "$(Agent.OS)"
          path: $(nodeModulesCache)
        displayName: Cache Node modules

      - script: |
          npm install
        displayName: 'npm install'

      - script: |
          ng build
        displayName: 'ng build'

      - task: ArchiveFiles@2
        displayName: 'Zip Web Artifact'
        inputs:
          rootFolderOrFile: 'dist'
          includeRootFolder: false
          archiveType: 'zip'
          archiveFile: '$(Build.ArtifactStagingDirectory)/UKSF.Web.zip'
          replaceExistingArchive: true

      - task: PublishBuildArtifacts@1
        displayName: 'Publish Artifact'
        inputs:
          PathtoPublish: '$(build.artifactstagingdirectory)/UKSF.Web.zip'
          ArtifactName: 'UKSF.Web'
          publishLocation: 'Container'
