trigger:
- main

pool: Avengers

jobs:
  - job: BuildPublish
    displayName: Build & Publish
    steps:
      - checkout: self
        clean: false

      - task: NodeTool@0
        inputs:
          versionSpec: '17.x'
        displayName: 'Install Node.js'

      - script: |
          npm install
        displayName: 'npm install'

      - script: |
          ng build -c production --aot --build-optimizer --optimization
        displayName: 'ng build'

      - task: ArchiveFiles@2
        displayName: 'Zip Web Artifact'
        inputs:
          rootFolderOrFile: 'dist'
          includeRootFolder: false
          archiveType: 'zip'
          archiveFile: '$(Build.ArtifactStagingDirectory)/UKSF.Web.zip'
          replaceExistingArchive: true

      - task: PublishBuildArtifacts@1
        displayName: 'Publish Artifact'
        inputs:
          PathtoPublish: '$(build.artifactstagingdirectory)/UKSF.Web.zip'
          ArtifactName: 'UKSF.Web'
          publishLocation: 'Container'
