trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli
    npm install
  displayName: 'npm install'

- script: |
    node --max-old-space-size=12228 ./node_modules/@angular/cli/bin/ng build --prod --aot --build-optimizer
  displayName: 'ng build'
